### ISSUE TITLE
Latest update to gulp command line

### ISSUE THREAD

**Issue by bewards** [dalcib/brackets-gulp#13]
With the latest update to the gulp command line (which is great), I noticed that when running gulp-default task in Brackets, it no longer auto-scrolls to the latest position. Is this just a user preference?

![image](https://cloud.githubusercontent.com/assets/3927169/6672945/feb43868-cbe5-11e4-9c22-764039839b41.png)

**Comment by dalcib** [comment]
Fix with https://github.com/dalcib/brackets-gulp/commit/0e461f8d2b7c23fcedece7ed8caf0f32d7c8d441 
Update to 0.3.1
