### ISSUE TITLE
Gulp Menue empty after Brackets 1.1

### ISSUE THREAD

**Issue by superwese** [dalcib/brackets-gulp#5]
Hi after updating to Brackets 1.1 the "Gulp" Menue shows only the default entry and the gulp console does not open. I can see no errors on startup. The gulpfile was found from the plugin ( I added a log statement to main.js ) and the plugin was working with the gulp file in Brackets 1.0

**Comment by amitmtrn** [comment]
+1

**Comment by dalcib** [comment]
Fix with https://github.com/dalcib/brackets-gulp/commit/ccc94b4dc39e9bf5723069bd71900b7c814e1fe7
I struggled a little with events but now is done.
