### ISSUE TITLE
Options to style output

### ISSUE THREAD

**Issue by thco** [dalcib/brackets-gulp#7]
Hi.

Is it possible to add some options settings for "pre" output style ? (Currently styled it myself but I think it could be a nice feature)

Thanks.

**Comment by dalcib** [comment]
Could you give me an example how to do it?

**Comment by thco** [comment]
Hum, not really. I'm starting using Brackets weeks ago, not very long time... I downloaded it as user, i'm not focusing on plugins development.
I just direct styling your "pre" tag in the html file...

But I thinking of tweaking this, there must be a way :-)
